trigger:
  - main  # Trigger on changes to the main branch

pool:
  name: 'notagent'

stages:
  - stage: Build
    displayName: Build Flask App
    jobs:
      - job: BuildJob
        displayName: Build the Flask application
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              python -m venv venv
              .\venv\Scripts\activate
              pip install -r requirements.txt
            displayName: Install Dependencies
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifactName: 'flask-app'

  - stage: Deploy
    displayName: Deploy Flask App
    dependsOn: Build
    jobs:
      - deployment: DeployToWindows
        displayName: Deploy to Windows Machine
        environment: 'WindowsDeployment'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: flask-app
                - script: |
                    python -m venv venv
                    .\venv\Scripts\activate
                    pip install -r requirements.txt
                    python wsgi.py
                  displayName: Run Flask App
